name: Deploy Odoo to AWS EC2

on:
  push:
    branches:
      - main
      - 17.0  # Nhánh mà bạn muốn triển khai

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to EC2
      run: |
        scp -r * ubuntu@your-ec2-public-ip:/home/ubuntu/odoo/

    - name: Install dependencies on EC2
      run: |
        ssh ubuntu@your-ec2-public-ip <<EOF
          cd /home/ubuntu/odoo
          sudo pip3 install -r requirements.txt
          sudo docker-compose up -d
        EOF
