name: Deploy Odoo to AWS EC2

on:
  push:
    branches:
      - 17.0   # Chạy workflow khi có bất kỳ lệnh push nào lên nhánh 17.0
  pull_request:
    branches:
      - 17.0   # Chạy workflow khi có pull request lên nhánh 17.0

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add EC2 to known hosts
      run: |
        ssh-keyscan -H 52.65.35.193 >> ~/.ssh/known_hosts

    - name: Create directory on EC2
      run: |
        ssh ubuntu@52.65.35.193 'mkdir -p /home/ubuntu/odoo/'

    - name: Copy files to EC2
      run: |
